import requests # requests>=2.31.0
import os
import pytest # pytest>=7.4.2

# Fixture to provide a sample image path for testing
@pytest.fixture
def image_path():
    return "data/val/dogs/82.jpg"

# Test to verify the API health endpoint
def test_health():
    # URL matches the default port used by the FastAPI app
    url = "http://localhost:8000/health"
    try:
        response = requests.get(url)
        print(f"Health Check: {response.json()}")
    except Exception as e:
        print(f"Health Check Failed: {e}")

# Test to verify the API prediction endpoint using a sample image
def test_predict(image_path):
    url = "http://localhost:8000/predict"
    if not os.path.exists(image_path):
        print(f"Image not found for testing: {image_path}")
        return

    try:
        with open(image_path, "rb") as f:
            files = {"file": f}
            response = requests.post(url, files=files)
            print(f"Prediction result: {response.json()}")
    except Exception as e:
        print(f"Prediction Failed: {e}")

if __name__ == "__main__":
    # Integration tests against a running API instance
    test_health()
    # Use a valid image path from the validation data generated by the pipeline
    test_image = "data/val/dogs/82.jpg"
    test_predict(test_image)
