artifact_location: file:///C:/Users/jmajjigi/OneDrive - Microsoft/Jambanna/Personal/MTech/SEM
  III/MLOPS/AssignmentII/mlruns_test/742916855699115835
creation_time: 1771421733707
experiment_id: '742916855699115835'
last_update_time: 1771421733707
lifecycle_stage: active
name: Repro_Experiment
