artifact_location: file:///C:/Users/jmajjigi/OneDrive - Microsoft/Jambanna/Personal/MTech/SEM
  III/MLOPS/AssignmentII/mlruns_test/0
creation_time: 1771421733418
experiment_id: '0'
last_update_time: 1771421733418
lifecycle_stage: active
name: Default
