artifact_uri: file:///C:/Users/jmajjigi/OneDrive - Microsoft/Jambanna/Personal/MTech/SEM
  III/MLOPS/AssignmentII/mlruns_test/742916855699115835/d44b349c74e44880b660a49e54419a49/artifacts
end_time: 1771421842142
entry_point_name: ''
experiment_id: '742916855699115835'
lifecycle_stage: active
run_id: d44b349c74e44880b660a49e54419a49
run_name: enchanting-yak-960
source_name: ''
source_type: 4
source_version: ''
start_time: 1771421752116
status: 3
tags: []
user_id: jmajjigi
